# -*- coding: utf-8 -*-
"""OTP PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144s1AtLY3oxrMtGHE6NH29fX64C27Gxt
"""

import pandas as pd
import numpy as np


data=pd.read_excel("mails.xlsx")

def otpfun():
  otp=np.random.randint(1000,10000)
  return otp


def validate_password (pw):
  special="!@#$%^&*"
  if (len(pw))<=6:
    print("Password must be more than 6 characters.")
    return False
  elif not any(ch in special for ch in pw ):
    print("Password must contain at least one special character.")
    return False
  else:
    return True


user=input("Enter UserName/Email : ")
if user in data["username"].values or user in data["email"].values:
  user_row=data[(data["username"]==user)|(data["email"]==user)]

  print("\n1. Login \n2.Forgot Password")
  ch = int(input("Enter your choice(1/2) : "))

  if ch==1:
    pw=input("Enter Password : ")
    if pw == user_row.iloc[0]["password"]:
      print("Logged in succesfully")
    else:
      print("Invalid Password")



  elif ch==2:
    attempts=3
    generated_otp = otpfun()
    print(generated_otp,"\nOTP sent successfully.")


    while attempts>0 :
      entered_otp=int(input("Enter OTP : "))

      if generated_otp==entered_otp:
        print("---*consists alphabets, numbers, special characters*--- ")
        p_w1=input("Enter new password : ")
        p_w2=input("Confirm new password : ")
        if p_w1==p_w2:
           if validate_password (p_w1):
            data.loc[user_row.index, "password"] = p_w1
            data.to_excel("mails.xlsx", index=False)
            print("password changed successfully")
            print("Please login again using your new password.")
            break
        else:
          print("NOT MATCHED!!")

      else:
        attempts-=1
        if attempts>0:
          print("ENTERED WRONG OTP")
          print("Remaing attempts - ", attempts)
        else:
          print("Maximum OTP attempts exceeded")



  else:
    print("invalid choice")



else:
  print("User Not Found")